-- All postcodes in Denmark
INSERT INTO City VALUES (555, 'Scanning');
INSERT INTO City VALUES (783, 'Facility');
INSERT INTO City VALUES (800, 'Høje Taastrup');
INSERT INTO City VALUES (877, 'København C');
INSERT INTO City VALUES (892, 'Sjælland USF P');
INSERT INTO City VALUES (893, 'Sjælland USF B');
INSERT INTO City VALUES (894, 'Udbetaling');
INSERT INTO City VALUES (899, 'Kommuneservice');
INSERT INTO City VALUES (900, 'København C');
INSERT INTO City VALUES (910, 'København C');
INSERT INTO City VALUES (913, 'Københavns Pakkecenter');
INSERT INTO City VALUES (914, 'Københavns Pakkecenter');
INSERT INTO City VALUES (917, 'Københavns Pakkecenter');
INSERT INTO City VALUES (918, 'Københavns Pakke BRC');
INSERT INTO City VALUES (919, 'Returprint BRC');
INSERT INTO City VALUES (929, 'København C');
INSERT INTO City VALUES (960, 'Internationalt Postcenter');
INSERT INTO City VALUES (999, 'København C');
INSERT INTO City VALUES (1001, 'København K');
INSERT INTO City VALUES (1002, 'København K');
INSERT INTO City VALUES (1003, 'København K');
INSERT INTO City VALUES (1004, 'København K');
INSERT INTO City VALUES (1005, 'København K');
INSERT INTO City VALUES (1006, 'København K');
INSERT INTO City VALUES (1007, 'København K');
INSERT INTO City VALUES (1008, 'København K');
INSERT INTO City VALUES (1009, 'København K');
INSERT INTO City VALUES (1010, 'København K');
INSERT INTO City VALUES (1011, 'København K');
INSERT INTO City VALUES (1012, 'København K');
INSERT INTO City VALUES (1013, 'København K');
INSERT INTO City VALUES (1014, 'København K');
INSERT INTO City VALUES (1015, 'København K');
INSERT INTO City VALUES (1016, 'København K');
INSERT INTO City VALUES (1017, 'København K');
INSERT INTO City VALUES (1018, 'København K');
INSERT INTO City VALUES (1019, 'København K');
INSERT INTO City VALUES (1020, 'København K');
INSERT INTO City VALUES (1021, 'København K');
INSERT INTO City VALUES (1022, 'København K');
INSERT INTO City VALUES (1023, 'København K');
INSERT INTO City VALUES (1024, 'København K');
INSERT INTO City VALUES (1025, 'København K');
INSERT INTO City VALUES (1026, 'København K');
INSERT INTO City VALUES (1045, 'København K');
INSERT INTO City VALUES (1050, 'København K');
INSERT INTO City VALUES (1051, 'København K');
INSERT INTO City VALUES (1052, 'København K');
INSERT INTO City VALUES (1053, 'København K');
INSERT INTO City VALUES (1054, 'København K');
INSERT INTO City VALUES (1055, 'København K');
INSERT INTO City VALUES (1056, 'København K');
INSERT INTO City VALUES (1057, 'København K');
INSERT INTO City VALUES (1058, 'København K');
INSERT INTO City VALUES (1059, 'København K');
INSERT INTO City VALUES (1060, 'København K');
INSERT INTO City VALUES (1061, 'København K');
INSERT INTO City VALUES (1062, 'København K');
INSERT INTO City VALUES (1063, 'København K');
INSERT INTO City VALUES (1064, 'København K');
INSERT INTO City VALUES (1065, 'København K');
INSERT INTO City VALUES (1066, 'København K');
INSERT INTO City VALUES (1067, 'København K');
INSERT INTO City VALUES (1068, 'København K');
INSERT INTO City VALUES (1069, 'København K');
INSERT INTO City VALUES (1070, 'København K');
INSERT INTO City VALUES (1071, 'København K');
INSERT INTO City VALUES (1072, 'København K');
INSERT INTO City VALUES (1073, 'København K');
INSERT INTO City VALUES (1074, 'København K');
INSERT INTO City VALUES (1092, 'København K');
INSERT INTO City VALUES (1093, 'København K');
INSERT INTO City VALUES (1095, 'København K');
INSERT INTO City VALUES (1098, 'København K');
INSERT INTO City VALUES (1100, 'København K');
INSERT INTO City VALUES (1101, 'København K');
INSERT INTO City VALUES (1102, 'København K');
INSERT INTO City VALUES (1103, 'København K');
INSERT INTO City VALUES (1104, 'København K');
INSERT INTO City VALUES (1105, 'København K');
INSERT INTO City VALUES (1106, 'København K');
INSERT INTO City VALUES (1107, 'København K');
INSERT INTO City VALUES (1110, 'København K');
INSERT INTO City VALUES (1111, 'København K');
INSERT INTO City VALUES (1112, 'København K');
INSERT INTO City VALUES (1113, 'København K');
INSERT INTO City VALUES (1114, 'København K');
INSERT INTO City VALUES (1115, 'København K');
INSERT INTO City VALUES (1116, 'København K');
INSERT INTO City VALUES (1117, 'København K');
INSERT INTO City VALUES (1118, 'København K');
INSERT INTO City VALUES (1119, 'København K');
INSERT INTO City VALUES (1120, 'København K');
INSERT INTO City VALUES (1121, 'København K');
INSERT INTO City VALUES (1122, 'København K');
INSERT INTO City VALUES (1123, 'København K');
INSERT INTO City VALUES (1124, 'København K');
INSERT INTO City VALUES (1125, 'København K');
INSERT INTO City VALUES (1126, 'København K');
INSERT INTO City VALUES (1127, 'København K');
INSERT INTO City VALUES (1128, 'København K');
INSERT INTO City VALUES (1129, 'København K');
INSERT INTO City VALUES (1130, 'København K');
INSERT INTO City VALUES (1131, 'København K');
INSERT INTO City VALUES (1140, 'København K');
INSERT INTO City VALUES (1147, 'København K');
INSERT INTO City VALUES (1148, 'København K');
INSERT INTO City VALUES (1150, 'København K');
INSERT INTO City VALUES (1151, 'København K');
INSERT INTO City VALUES (1152, 'København K');
INSERT INTO City VALUES (1153, 'København K');
INSERT INTO City VALUES (1154, 'København K');
INSERT INTO City VALUES (1155, 'København K');
INSERT INTO City VALUES (1156, 'København K');
INSERT INTO City VALUES (1157, 'København K');
INSERT INTO City VALUES (1158, 'København K');
INSERT INTO City VALUES (1159, 'København K');
INSERT INTO City VALUES (1160, 'København K');
INSERT INTO City VALUES (1161, 'København K');
INSERT INTO City VALUES (1162, 'København K');
INSERT INTO City VALUES (1164, 'København K');
INSERT INTO City VALUES (1165, 'København K');
INSERT INTO City VALUES (1166, 'København K');
INSERT INTO City VALUES (1167, 'København K');
INSERT INTO City VALUES (1168, 'København K');
INSERT INTO City VALUES (1169, 'København K');
INSERT INTO City VALUES (1170, 'København K');
INSERT INTO City VALUES (1171, 'København K');
INSERT INTO City VALUES (1172, 'København K');
INSERT INTO City VALUES (1173, 'København K');
INSERT INTO City VALUES (1174, 'København K');
INSERT INTO City VALUES (1175, 'København K');
INSERT INTO City VALUES (1200, 'København K');
INSERT INTO City VALUES (1201, 'København K');
INSERT INTO City VALUES (1202, 'København K');
INSERT INTO City VALUES (1203, 'København K');
INSERT INTO City VALUES (1204, 'København K');
INSERT INTO City VALUES (1205, 'København K');
INSERT INTO City VALUES (1206, 'København K');
INSERT INTO City VALUES (1207, 'København K');
INSERT INTO City VALUES (1208, 'København K');
INSERT INTO City VALUES (1209, 'København K');
INSERT INTO City VALUES (1210, 'København K');
INSERT INTO City VALUES (1211, 'København K');
INSERT INTO City VALUES (1212, 'København K');
INSERT INTO City VALUES (1213, 'København K');
INSERT INTO City VALUES (1214, 'København K');
INSERT INTO City VALUES (1215, 'København K');
INSERT INTO City VALUES (1216, 'København K');
INSERT INTO City VALUES (1217, 'København K');
INSERT INTO City VALUES (1218, 'København K');
INSERT INTO City VALUES (1219, 'København K');
INSERT INTO City VALUES (1220, 'København K');
INSERT INTO City VALUES (1221, 'København K');
INSERT INTO City VALUES (1240, 'København K');
INSERT INTO City VALUES (1250, 'København K');
INSERT INTO City VALUES (1251, 'København K');
INSERT INTO City VALUES (1252, 'København K');
INSERT INTO City VALUES (1253, 'København K');
INSERT INTO City VALUES (1254, 'København K');
INSERT INTO City VALUES (1255, 'København K');
INSERT INTO City VALUES (1256, 'København K');
INSERT INTO City VALUES (1257, 'København K');
INSERT INTO City VALUES (1260, 'København K');
INSERT INTO City VALUES (1261, 'København K');
INSERT INTO City VALUES (1263, 'København K');
INSERT INTO City VALUES (1264, 'København K');
INSERT INTO City VALUES (1265, 'København K');
INSERT INTO City VALUES (1266, 'København K');
INSERT INTO City VALUES (1267, 'København K');
INSERT INTO City VALUES (1268, 'København K');
INSERT INTO City VALUES (1270, 'København K');
INSERT INTO City VALUES (1271, 'København K');
INSERT INTO City VALUES (1300, 'København K');
INSERT INTO City VALUES (1301, 'København K');
INSERT INTO City VALUES (1302, 'København K');
INSERT INTO City VALUES (1303, 'København K');
INSERT INTO City VALUES (1304, 'København K');
INSERT INTO City VALUES (1306, 'København K');
INSERT INTO City VALUES (1307, 'København K');
INSERT INTO City VALUES (1308, 'København K');
INSERT INTO City VALUES (1309, 'København K');
INSERT INTO City VALUES (1310, 'København K');
INSERT INTO City VALUES (1311, 'København K');
INSERT INTO City VALUES (1312, 'København K');
INSERT INTO City VALUES (1313, 'København K');
INSERT INTO City VALUES (1314, 'København K');
INSERT INTO City VALUES (1315, 'København K');
INSERT INTO City VALUES (1316, 'København K');
INSERT INTO City VALUES (1317, 'København K');
INSERT INTO City VALUES (1318, 'København K');
INSERT INTO City VALUES (1319, 'København K');
INSERT INTO City VALUES (1320, 'København K');
INSERT INTO City VALUES (1321, 'København K');
INSERT INTO City VALUES (1322, 'København K');
INSERT INTO City VALUES (1323, 'København K');
INSERT INTO City VALUES (1324, 'København K');
INSERT INTO City VALUES (1325, 'København K');
INSERT INTO City VALUES (1326, 'København K');
INSERT INTO City VALUES (1327, 'København K');
INSERT INTO City VALUES (1328, 'København K');
INSERT INTO City VALUES (1329, 'København K');
INSERT INTO City VALUES (1350, 'København K');
INSERT INTO City VALUES (1352, 'København K');
INSERT INTO City VALUES (1353, 'København K');
INSERT INTO City VALUES (1354, 'København K');
INSERT INTO City VALUES (1355, 'København K');
INSERT INTO City VALUES (1356, 'København K');
INSERT INTO City VALUES (1357, 'København K');
INSERT INTO City VALUES (1358, 'København K');
INSERT INTO City VALUES (1359, 'København K');
INSERT INTO City VALUES (1360, 'København K');
INSERT INTO City VALUES (1361, 'København K');
INSERT INTO City VALUES (1362, 'København K');
INSERT INTO City VALUES (1363, 'København K');
INSERT INTO City VALUES (1364, 'København K');
INSERT INTO City VALUES (1365, 'København K');
INSERT INTO City VALUES (1366, 'København K');
INSERT INTO City VALUES (1367, 'København K');
INSERT INTO City VALUES (1368, 'København K');
INSERT INTO City VALUES (1369, 'København K');
INSERT INTO City VALUES (1370, 'København K');
INSERT INTO City VALUES (1371, 'København K');
INSERT INTO City VALUES (1400, 'København K');
INSERT INTO City VALUES (1401, 'København K');
INSERT INTO City VALUES (1402, 'København K');
INSERT INTO City VALUES (1403, 'København K');
INSERT INTO City VALUES (1406, 'København K');
INSERT INTO City VALUES (1407, 'København K');
INSERT INTO City VALUES (1408, 'København K');
INSERT INTO City VALUES (1409, 'København K');
INSERT INTO City VALUES (1410, 'København K');
INSERT INTO City VALUES (1411, 'København K');
INSERT INTO City VALUES (1412, 'København K');
INSERT INTO City VALUES (1413, 'København K');
INSERT INTO City VALUES (1414, 'København K');
INSERT INTO City VALUES (1415, 'København K');
INSERT INTO City VALUES (1416, 'København K');
INSERT INTO City VALUES (1417, 'København K');
INSERT INTO City VALUES (1418, 'København K');
INSERT INTO City VALUES (1419, 'København K');
INSERT INTO City VALUES (1420, 'København K');
INSERT INTO City VALUES (1421, 'København K');
INSERT INTO City VALUES (1422, 'København K');
INSERT INTO City VALUES (1423, 'København K');
INSERT INTO City VALUES (1424, 'København K');
INSERT INTO City VALUES (1425, 'København K');
INSERT INTO City VALUES (1426, 'København K');
INSERT INTO City VALUES (1427, 'København K');
INSERT INTO City VALUES (1428, 'København K');
INSERT INTO City VALUES (1429, 'København K');
INSERT INTO City VALUES (1430, 'København K');
INSERT INTO City VALUES (1432, 'København K');
INSERT INTO City VALUES (1433, 'København K');
INSERT INTO City VALUES (1434, 'København K');
INSERT INTO City VALUES (1435, 'København K');
INSERT INTO City VALUES (1436, 'København K');
INSERT INTO City VALUES (1437, 'København K');
INSERT INTO City VALUES (1438, 'København K');
INSERT INTO City VALUES (1439, 'København K');
INSERT INTO City VALUES (1440, 'København K');
INSERT INTO City VALUES (1441, 'København K');
INSERT INTO City VALUES (1448, 'København K');
INSERT INTO City VALUES (1450, 'København K');
INSERT INTO City VALUES (1451, 'København K');
INSERT INTO City VALUES (1452, 'København K');
INSERT INTO City VALUES (1453, 'København K');
INSERT INTO City VALUES (1454, 'København K');
INSERT INTO City VALUES (1455, 'København K');
INSERT INTO City VALUES (1456, 'København K');
INSERT INTO City VALUES (1457, 'København K');
INSERT INTO City VALUES (1458, 'København K');
INSERT INTO City VALUES (1459, 'København K');
INSERT INTO City VALUES (1460, 'København K');
INSERT INTO City VALUES (1461, 'København K');
INSERT INTO City VALUES (1462, 'København K');
INSERT INTO City VALUES (1463, 'København K');
INSERT INTO City VALUES (1464, 'København K');
INSERT INTO City VALUES (1465, 'København K');
INSERT INTO City VALUES (1466, 'København K');
INSERT INTO City VALUES (1467, 'København K');
INSERT INTO City VALUES (1468, 'København K');
INSERT INTO City VALUES (1470, 'København K');
INSERT INTO City VALUES (1471, 'København K');
INSERT INTO City VALUES (1472, 'København K');
INSERT INTO City VALUES (1473, 'København K');
INSERT INTO City VALUES (1500, 'København V');
INSERT INTO City VALUES (1501, 'København V');
INSERT INTO City VALUES (1502, 'København V');
INSERT INTO City VALUES (1503, 'København V');
INSERT INTO City VALUES (1504, 'København V');
INSERT INTO City VALUES (1505, 'København V');
INSERT INTO City VALUES (1506, 'København V');
INSERT INTO City VALUES (1507, 'København V');
INSERT INTO City VALUES (1508, 'København V');
INSERT INTO City VALUES (1509, 'København V');
INSERT INTO City VALUES (1510, 'København V');
INSERT INTO City VALUES (1512, 'Returpost');
INSERT INTO City VALUES (1513, 'Flytninger og Nejtak');
INSERT INTO City VALUES (1532, 'København V');
INSERT INTO City VALUES (1533, 'København V');
INSERT INTO City VALUES (1550, 'København V');
INSERT INTO City VALUES (1551, 'København V');
INSERT INTO City VALUES (1552, 'København V');
INSERT INTO City VALUES (1553, 'København V');
INSERT INTO City VALUES (1554, 'København V');
INSERT INTO City VALUES (1555, 'København V');
INSERT INTO City VALUES (1556, 'København V');
INSERT INTO City VALUES (1557, 'København V');
INSERT INTO City VALUES (1558, 'København V');
INSERT INTO City VALUES (1559, 'København V');
INSERT INTO City VALUES (1560, 'København V');
INSERT INTO City VALUES (1561, 'København V');
INSERT INTO City VALUES (1562, 'København V');
INSERT INTO City VALUES (1563, 'København V');
INSERT INTO City VALUES (1564, 'København V');
INSERT INTO City VALUES (1567, 'København V');
INSERT INTO City VALUES (1568, 'København V');
INSERT INTO City VALUES (1569, 'København V');
INSERT INTO City VALUES (1570, 'København V');
INSERT INTO City VALUES (1571, 'København V');
INSERT INTO City VALUES (1572, 'København V');
INSERT INTO City VALUES (1573, 'København V');
INSERT INTO City VALUES (1574, 'København V');
INSERT INTO City VALUES (1575, 'København V');
INSERT INTO City VALUES (1576, 'København V');
INSERT INTO City VALUES (1577, 'København V');
INSERT INTO City VALUES (1592, 'København V');
INSERT INTO City VALUES (1599, 'København V');
INSERT INTO City VALUES (1600, 'København V');
INSERT INTO City VALUES (1601, 'København V');
INSERT INTO City VALUES (1602, 'København V');
INSERT INTO City VALUES (1603, 'København V');
INSERT INTO City VALUES (1604, 'København V');
INSERT INTO City VALUES (1605, 'København V');
INSERT INTO City VALUES (1606, 'København V');
INSERT INTO City VALUES (1607, 'København V');
INSERT INTO City VALUES (1608, 'København V');
INSERT INTO City VALUES (1609, 'København V');
INSERT INTO City VALUES (1610, 'København V');
INSERT INTO City VALUES (1611, 'København V');
INSERT INTO City VALUES (1612, 'København V');
INSERT INTO City VALUES (1613, 'København V');
INSERT INTO City VALUES (1614, 'København V');
INSERT INTO City VALUES (1615, 'København V');
INSERT INTO City VALUES (1616, 'København V');
INSERT INTO City VALUES (1617, 'København V');
INSERT INTO City VALUES (1618, 'København V');
INSERT INTO City VALUES (1619, 'København V');
INSERT INTO City VALUES (1620, 'København V');
INSERT INTO City VALUES (1621, 'København V');
INSERT INTO City VALUES (1622, 'København V');
INSERT INTO City VALUES (1623, 'København V');
INSERT INTO City VALUES (1624, 'København V');
INSERT INTO City VALUES (1630, 'København V');
INSERT INTO City VALUES (1631, 'København V');
INSERT INTO City VALUES (1632, 'København V');
INSERT INTO City VALUES (1633, 'København V');
INSERT INTO City VALUES (1634, 'København V');
INSERT INTO City VALUES (1635, 'København V');
INSERT INTO City VALUES (1650, 'København V');
INSERT INTO City VALUES (1651, 'København V');
INSERT INTO City VALUES (1652, 'København V');
INSERT INTO City VALUES (1653, 'København V');
INSERT INTO City VALUES (1654, 'København V');
INSERT INTO City VALUES (1655, 'København V');
INSERT INTO City VALUES (1656, 'København V');
INSERT INTO City VALUES (1657, 'København V');
INSERT INTO City VALUES (1658, 'København V');
INSERT INTO City VALUES (1659, 'København V');
INSERT INTO City VALUES (1660, 'København V');
INSERT INTO City VALUES (1661, 'København V');
INSERT INTO City VALUES (1662, 'København V');
INSERT INTO City VALUES (1663, 'København V');
INSERT INTO City VALUES (1664, 'København V');
INSERT INTO City VALUES (1665, 'København V');
INSERT INTO City VALUES (1666, 'København V');
INSERT INTO City VALUES (1667, 'København V');
INSERT INTO City VALUES (1668, 'København V');
INSERT INTO City VALUES (1669, 'København V');
INSERT INTO City VALUES (1670, 'København V');
INSERT INTO City VALUES (1671, 'København V');
INSERT INTO City VALUES (1672, 'København V');
INSERT INTO City VALUES (1673, 'København V');
INSERT INTO City VALUES (1674, 'København V');
INSERT INTO City VALUES (1675, 'København V');
INSERT INTO City VALUES (1676, 'København V');
INSERT INTO City VALUES (1677, 'København V');
INSERT INTO City VALUES (1699, 'København V');
INSERT INTO City VALUES (1700, 'København V');
INSERT INTO City VALUES (1701, 'København V');
INSERT INTO City VALUES (1702, 'København V');
INSERT INTO City VALUES (1703, 'København V');
INSERT INTO City VALUES (1704, 'København V');
INSERT INTO City VALUES (1705, 'København V');
INSERT INTO City VALUES (1706, 'København V');
INSERT INTO City VALUES (1707, 'København V');
INSERT INTO City VALUES (1708, 'København V');
INSERT INTO City VALUES (1709, 'København V');
INSERT INTO City VALUES (1710, 'København V');
INSERT INTO City VALUES (1711, 'København V');
INSERT INTO City VALUES (1712, 'København V');
INSERT INTO City VALUES (1714, 'København V');
INSERT INTO City VALUES (1715, 'København V');
INSERT INTO City VALUES (1716, 'København V');
INSERT INTO City VALUES (1717, 'København V');
INSERT INTO City VALUES (1718, 'København V');
INSERT INTO City VALUES (1719, 'København V');
INSERT INTO City VALUES (1720, 'København V');
INSERT INTO City VALUES (1721, 'København V');
INSERT INTO City VALUES (1722, 'København V');
INSERT INTO City VALUES (1723, 'København V');
INSERT INTO City VALUES (1724, 'København V');
INSERT INTO City VALUES (1725, 'København V');
INSERT INTO City VALUES (1726, 'København V');
INSERT INTO City VALUES (1727, 'København V');
INSERT INTO City VALUES (1728, 'København V');
INSERT INTO City VALUES (1729, 'København V');
INSERT INTO City VALUES (1730, 'København V');
INSERT INTO City VALUES (1731, 'København V');
INSERT INTO City VALUES (1732, 'København V');
INSERT INTO City VALUES (1733, 'København V');
INSERT INTO City VALUES (1734, 'København V');
INSERT INTO City VALUES (1735, 'København V');
INSERT INTO City VALUES (1736, 'København V');
INSERT INTO City VALUES (1737, 'København V');
INSERT INTO City VALUES (1738, 'København V');
INSERT INTO City VALUES (1739, 'København V');
INSERT INTO City VALUES (1749, 'København V');
INSERT INTO City VALUES (1750, 'København V');
INSERT INTO City VALUES (1751, 'København V');
INSERT INTO City VALUES (1752, 'København V');
INSERT INTO City VALUES (1753, 'København V');
INSERT INTO City VALUES (1754, 'København V');
INSERT INTO City VALUES (1755, 'København V');
INSERT INTO City VALUES (1756, 'København V');
INSERT INTO City VALUES (1757, 'København V');
INSERT INTO City VALUES (1758, 'København V');
INSERT INTO City VALUES (1759, 'København V');
INSERT INTO City VALUES (1760, 'København V');
INSERT INTO City VALUES (1761, 'København V');
INSERT INTO City VALUES (1762, 'København V');
INSERT INTO City VALUES (1763, 'København V');
INSERT INTO City VALUES (1764, 'København V');
INSERT INTO City VALUES (1765, 'København V');
INSERT INTO City VALUES (1766, 'København V');
INSERT INTO City VALUES (1770, 'København V');
INSERT INTO City VALUES (1771, 'København V');
INSERT INTO City VALUES (1772, 'København V');
INSERT INTO City VALUES (1773, 'København V');
INSERT INTO City VALUES (1774, 'København V');
INSERT INTO City VALUES (1775, 'København V');
INSERT INTO City VALUES (1777, 'København V');
INSERT INTO City VALUES (1780, 'København V');
INSERT INTO City VALUES (1782, 'København V');
INSERT INTO City VALUES (1785, 'København V');
INSERT INTO City VALUES (1786, 'København V');
INSERT INTO City VALUES (1787, 'København V');
INSERT INTO City VALUES (1790, 'København V');
INSERT INTO City VALUES (1799, 'København V');
INSERT INTO City VALUES (1800, 'Frederiksberg C');
INSERT INTO City VALUES (1801, 'Frederiksberg C');
INSERT INTO City VALUES (1802, 'Frederiksberg C');
INSERT INTO City VALUES (1803, 'Frederiksberg C');
INSERT INTO City VALUES (1804, 'Frederiksberg C');
INSERT INTO City VALUES (1805, 'Frederiksberg C');
INSERT INTO City VALUES (1806, 'Frederiksberg C');
INSERT INTO City VALUES (1807, 'Frederiksberg C');
INSERT INTO City VALUES (1808, 'Frederiksberg C');
INSERT INTO City VALUES (1809, 'Frederiksberg C');
INSERT INTO City VALUES (1810, 'Frederiksberg C');
INSERT INTO City VALUES (1811, 'Frederiksberg C');
INSERT INTO City VALUES (1812, 'Frederiksberg C');
INSERT INTO City VALUES (1813, 'Frederiksberg C');
INSERT INTO City VALUES (1814, 'Frederiksberg C');
INSERT INTO City VALUES (1815, 'Frederiksberg C');
INSERT INTO City VALUES (1816, 'Frederiksberg C');
INSERT INTO City VALUES (1817, 'Frederiksberg C');
INSERT INTO City VALUES (1818, 'Frederiksberg C');
INSERT INTO City VALUES (1819, 'Frederiksberg C');
INSERT INTO City VALUES (1820, 'Frederiksberg C');
INSERT INTO City VALUES (1822, 'Frederiksberg C');
INSERT INTO City VALUES (1823, 'Frederiksberg C');
INSERT INTO City VALUES (1824, 'Frederiksberg C');
INSERT INTO City VALUES (1825, 'Frederiksberg C');
INSERT INTO City VALUES (1826, 'Frederiksberg C');
INSERT INTO City VALUES (1827, 'Frederiksberg C');
INSERT INTO City VALUES (1828, 'Frederiksberg C');
INSERT INTO City VALUES (1829, 'Frederiksberg C');
INSERT INTO City VALUES (1835, 'Frederiksberg C');
INSERT INTO City VALUES (1850, 'Frederiksberg C');
INSERT INTO City VALUES (1851, 'Frederiksberg C');
INSERT INTO City VALUES (1852, 'Frederiksberg C');
INSERT INTO City VALUES (1853, 'Frederiksberg C');
INSERT INTO City VALUES (1854, 'Frederiksberg C');
INSERT INTO City VALUES (1855, 'Frederiksberg C');
INSERT INTO City VALUES (1856, 'Frederiksberg C');
INSERT INTO City VALUES (1857, 'Frederiksberg C');
INSERT INTO City VALUES (1860, 'Frederiksberg C');
INSERT INTO City VALUES (1861, 'Frederiksberg C');
INSERT INTO City VALUES (1862, 'Frederiksberg C');
INSERT INTO City VALUES (1863, 'Frederiksberg C');
INSERT INTO City VALUES (1864, 'Frederiksberg C');
INSERT INTO City VALUES (1865, 'Frederiksberg C');
INSERT INTO City VALUES (1866, 'Frederiksberg C');
INSERT INTO City VALUES (1867, 'Frederiksberg C');
INSERT INTO City VALUES (1868, 'Frederiksberg C');
INSERT INTO City VALUES (1870, 'Frederiksberg C');
INSERT INTO City VALUES (1871, 'Frederiksberg C');
INSERT INTO City VALUES (1872, 'Frederiksberg C');
INSERT INTO City VALUES (1873, 'Frederiksberg C');
INSERT INTO City VALUES (1874, 'Frederiksberg C');
INSERT INTO City VALUES (1875, 'Frederiksberg C');
INSERT INTO City VALUES (1876, 'Frederiksberg C');
INSERT INTO City VALUES (1877, 'Frederiksberg C');
INSERT INTO City VALUES (1878, 'Frederiksberg C');
INSERT INTO City VALUES (1879, 'Frederiksberg C');
INSERT INTO City VALUES (1900, 'Frederiksberg C');
INSERT INTO City VALUES (1901, 'Frederiksberg C');
INSERT INTO City VALUES (1902, 'Frederiksberg C');
INSERT INTO City VALUES (1903, 'Frederiksberg C');
INSERT INTO City VALUES (1904, 'Frederiksberg C');
INSERT INTO City VALUES (1905, 'Frederiksberg C');
INSERT INTO City VALUES (1906, 'Frederiksberg C');
INSERT INTO City VALUES (1908, 'Frederiksberg C');
INSERT INTO City VALUES (1909, 'Frederiksberg C');
INSERT INTO City VALUES (1910, 'Frederiksberg C');
INSERT INTO City VALUES (1911, 'Frederiksberg C');
INSERT INTO City VALUES (1912, 'Frederiksberg C');
INSERT INTO City VALUES (1913, 'Frederiksberg C');
INSERT INTO City VALUES (1914, 'Frederiksberg C');
INSERT INTO City VALUES (1915, 'Frederiksberg C');
INSERT INTO City VALUES (1916, 'Frederiksberg C');
INSERT INTO City VALUES (1917, 'Frederiksberg C');
INSERT INTO City VALUES (1920, 'Frederiksberg C');
INSERT INTO City VALUES (1921, 'Frederiksberg C');
INSERT INTO City VALUES (1922, 'Frederiksberg C');
INSERT INTO City VALUES (1923, 'Frederiksberg C');
INSERT INTO City VALUES (1924, 'Frederiksberg C');
INSERT INTO City VALUES (1925, 'Frederiksberg C');
INSERT INTO City VALUES (1926, 'Frederiksberg C');
INSERT INTO City VALUES (1927, 'Frederiksberg C');
INSERT INTO City VALUES (1928, 'Frederiksberg C');
INSERT INTO City VALUES (1931, 'Frederiksberg C');
INSERT INTO City VALUES (1950, 'Frederiksberg C');
INSERT INTO City VALUES (1951, 'Frederiksberg C');
INSERT INTO City VALUES (1952, 'Frederiksberg C');
INSERT INTO City VALUES (1953, 'Frederiksberg C');
INSERT INTO City VALUES (1954, 'Frederiksberg C');
INSERT INTO City VALUES (1955, 'Frederiksberg C');
INSERT INTO City VALUES (1956, 'Frederiksberg C');
INSERT INTO City VALUES (1957, 'Frederiksberg C');
INSERT INTO City VALUES (1958, 'Frederiksberg C');
INSERT INTO City VALUES (1959, 'Frederiksberg C');
INSERT INTO City VALUES (1960, 'Frederiksberg C');
INSERT INTO City VALUES (1961, 'Frederiksberg C');
INSERT INTO City VALUES (1962, 'Frederiksberg C');
INSERT INTO City VALUES (1963, 'Frederiksberg C');
INSERT INTO City VALUES (1964, 'Frederiksberg C');
INSERT INTO City VALUES (1965, 'Frederiksberg C');
INSERT INTO City VALUES (1966, 'Frederiksberg C');
INSERT INTO City VALUES (1967, 'Frederiksberg C');
INSERT INTO City VALUES (1970, 'Frederiksberg C');
INSERT INTO City VALUES (1971, 'Frederiksberg C');
INSERT INTO City VALUES (1972, 'Frederiksberg C');
INSERT INTO City VALUES (1973, 'Frederiksberg C');
INSERT INTO City VALUES (1974, 'Frederiksberg C');
INSERT INTO City VALUES (2000, 'Frederiksberg');
INSERT INTO City VALUES (2100, 'København Ø');
INSERT INTO City VALUES (2150, 'Nordhavn');
INSERT INTO City VALUES (2200, 'København ');
INSERT INTO City VALUES (2300, 'København S');
INSERT INTO City VALUES (2400, 'København NV');
INSERT INTO City VALUES (2412, 'Grønland');
INSERT INTO City VALUES (2450, 'København SV');
INSERT INTO City VALUES (2500, 'Valby');
INSERT INTO City VALUES (2600, 'Glostrup');
INSERT INTO City VALUES (2605, 'Brøndby');
INSERT INTO City VALUES (2610, 'Rødovre');
INSERT INTO City VALUES (2620, 'Albertslund');
INSERT INTO City VALUES (2625, 'Vallensbæk');
INSERT INTO City VALUES (2630, 'Taastrup');
INSERT INTO City VALUES (2635, 'Ishøj');
INSERT INTO City VALUES (2640, 'Hedehusene');
INSERT INTO City VALUES (2650, 'Hvidovre');
INSERT INTO City VALUES (2660, 'Brøndby Strand');
INSERT INTO City VALUES (2665, 'Vallensbæk Strand');
INSERT INTO City VALUES (2670, 'Greve');
INSERT INTO City VALUES (2680, 'Solrød Strand');
INSERT INTO City VALUES (2690, 'Karlslunde');
INSERT INTO City VALUES (2700, 'Brønshøj');
INSERT INTO City VALUES (2720, 'Vanløse');
INSERT INTO City VALUES (2730, 'Herlev');
INSERT INTO City VALUES (2740, 'Skovlunde');
INSERT INTO City VALUES (2750, 'Ballerup');
INSERT INTO City VALUES (2760, 'Måløv');
INSERT INTO City VALUES (2765, 'Smørum');
INSERT INTO City VALUES (2770, 'Kastrup');
INSERT INTO City VALUES (2791, 'Dragør');
INSERT INTO City VALUES (2800, 'Kongens Lyngby');
INSERT INTO City VALUES (2820, 'Gentofte');
INSERT INTO City VALUES (2830, 'Virum');
INSERT INTO City VALUES (2840, 'Holte');
INSERT INTO City VALUES (2850, 'Nærum');
INSERT INTO City VALUES (2860, 'Søborg');
INSERT INTO City VALUES (2870, 'Dyssegård');
INSERT INTO City VALUES (2880, 'Bagsværd');
INSERT INTO City VALUES (2900, 'Hellerup');
INSERT INTO City VALUES (2920, 'Charlottenlund');
INSERT INTO City VALUES (2930, 'Klampenborg');
INSERT INTO City VALUES (2942, 'Skodsborg');
INSERT INTO City VALUES (2950, 'Vedbæk');
INSERT INTO City VALUES (2960, 'Rungsted Kyst');
INSERT INTO City VALUES (2970, 'Hørsholm');
INSERT INTO City VALUES (2980, 'Kokkedal');
INSERT INTO City VALUES (2990, 'Nivå');
INSERT INTO City VALUES (3000, 'Helsingør');
INSERT INTO City VALUES (3050, 'Humlebæk');
INSERT INTO City VALUES (3060, 'Espergærde');
INSERT INTO City VALUES (3070, 'Snekkersten');
INSERT INTO City VALUES (3080, 'Tikøb');
INSERT INTO City VALUES (3100, 'Hornbæk');
INSERT INTO City VALUES (3120, 'Dronningmølle');
INSERT INTO City VALUES (3140, 'Ålsgårde');
INSERT INTO City VALUES (3150, 'Hellebæk');
INSERT INTO City VALUES (3200, 'Helsinge');
INSERT INTO City VALUES (3210, 'Vejby');
INSERT INTO City VALUES (3220, 'Tisvildeleje');
INSERT INTO City VALUES (3230, 'Græsted');
INSERT INTO City VALUES (3250, 'Gilleleje');
INSERT INTO City VALUES (3300, 'Frederiksværk');
INSERT INTO City VALUES (3310, 'Ølsted');
INSERT INTO City VALUES (3320, 'Skævinge');
INSERT INTO City VALUES (3330, 'Gørløse');
INSERT INTO City VALUES (3360, 'Liseleje');
INSERT INTO City VALUES (3370, 'Melby');
INSERT INTO City VALUES (3390, 'Hundested');
INSERT INTO City VALUES (3400, 'Hillerød');
INSERT INTO City VALUES (3450, 'Allerød');
INSERT INTO City VALUES (3460, 'Birkerød');
INSERT INTO City VALUES (3480, 'Fredensborg');
INSERT INTO City VALUES (3490, 'Kvistgård');
INSERT INTO City VALUES (3500, 'Værløse');
INSERT INTO City VALUES (3520, 'Farum');
INSERT INTO City VALUES (3540, 'Lynge');
INSERT INTO City VALUES (3550, 'Slangerup');
INSERT INTO City VALUES (3600, 'Frederikssund');
INSERT INTO City VALUES (3630, 'Jægerspris');
INSERT INTO City VALUES (3650, 'Ølstykke');
INSERT INTO City VALUES (3660, 'Stenløse');
INSERT INTO City VALUES (3670, 'Veksø Sjælland');
INSERT INTO City VALUES (3700, 'Rønne');
INSERT INTO City VALUES (3720, 'Aakirkeby');
INSERT INTO City VALUES (3730, 'Nexø');
INSERT INTO City VALUES (3740, 'Svaneke');
INSERT INTO City VALUES (3751, 'Østermarie');
INSERT INTO City VALUES (3760, 'Gudhjem');
INSERT INTO City VALUES (3770, 'Allinge');
INSERT INTO City VALUES (3782, 'Klemensker');
INSERT INTO City VALUES (3790, 'Hasle');
INSERT INTO City VALUES (4000, 'Roskilde');
INSERT INTO City VALUES (4030, 'Tune');
INSERT INTO City VALUES (4040, 'Jyllinge');
INSERT INTO City VALUES (4050, 'Skibby');
INSERT INTO City VALUES (4060, 'Kirke Såby');
INSERT INTO City VALUES (4070, 'Kirke Hyllinge');
INSERT INTO City VALUES (4100, 'Ringsted');
INSERT INTO City VALUES (4129, 'Ringsted');
INSERT INTO City VALUES (4130, 'Viby Sjælland');
INSERT INTO City VALUES (4140, 'Borup');
INSERT INTO City VALUES (4160, 'Herlufmagle');
INSERT INTO City VALUES (4171, 'Glumsø');
INSERT INTO City VALUES (4173, 'Fjenneslev');
INSERT INTO City VALUES (4174, 'Jystrup Midtsj');
INSERT INTO City VALUES (4180, 'Sorø');
INSERT INTO City VALUES (4190, 'Munke Bjergby');
INSERT INTO City VALUES (4200, 'Slagelse');
INSERT INTO City VALUES (4220, 'Korsør');
INSERT INTO City VALUES (4230, 'Skælskør');
INSERT INTO City VALUES (4241, 'Vemmelev');
INSERT INTO City VALUES (4242, 'Boeslunde');
INSERT INTO City VALUES (4243, 'Rude');
INSERT INTO City VALUES (4244, 'Agersø');
INSERT INTO City VALUES (4245, 'Omø');
INSERT INTO City VALUES (4250, 'Fuglebjerg');
INSERT INTO City VALUES (4261, 'Dalmose');
INSERT INTO City VALUES (4262, 'Sandved');
INSERT INTO City VALUES (4270, 'Høng');
INSERT INTO City VALUES (4281, 'Gørlev');
INSERT INTO City VALUES (4291, 'Ruds Vedby');
INSERT INTO City VALUES (4293, 'Dianalund');
INSERT INTO City VALUES (4295, 'Stenlille');
INSERT INTO City VALUES (4296, 'Nyrup');
INSERT INTO City VALUES (4300, 'Holbæk');
INSERT INTO City VALUES (4305, 'Orø');
INSERT INTO City VALUES (4320, 'Lejre');
INSERT INTO City VALUES (4330, 'Hvalsø');
INSERT INTO City VALUES (4340, 'Tølløse');
INSERT INTO City VALUES (4350, 'Ugerløse');
INSERT INTO City VALUES (4360, 'Kirke Eskilstrup');
INSERT INTO City VALUES (4370, 'Store Merløse');
INSERT INTO City VALUES (4390, 'Vipperød');
INSERT INTO City VALUES (4400, 'Kalundborg');
INSERT INTO City VALUES (4420, 'Regstrup');
INSERT INTO City VALUES (4440, 'Mørkøv');
INSERT INTO City VALUES (4450, 'Jyderup');
INSERT INTO City VALUES (4460, 'Snertinge');
INSERT INTO City VALUES (4470, 'Svebølle');
INSERT INTO City VALUES (4480, 'Store Fuglede');
INSERT INTO City VALUES (4490, 'Jerslev Sjælland');
INSERT INTO City VALUES (4500, 'Nykøbing Sj');
INSERT INTO City VALUES (4520, 'Svinninge');
INSERT INTO City VALUES (4532, 'Gislinge');
INSERT INTO City VALUES (4534, 'Hørve');
INSERT INTO City VALUES (4540, 'Fårevejle');
INSERT INTO City VALUES (4550, 'Asnæs');
INSERT INTO City VALUES (4560, 'Vig');
INSERT INTO City VALUES (4571, 'Grevinge');
INSERT INTO City VALUES (4572, 'Nørre Asmindrup');
INSERT INTO City VALUES (4573, 'Højby');
INSERT INTO City VALUES (4581, 'Rørvig');
INSERT INTO City VALUES (4583, 'Sjællands Odde');
INSERT INTO City VALUES (4591, 'Føllenslev');
INSERT INTO City VALUES (4592, 'Sejerø');
INSERT INTO City VALUES (4593, 'Eskebjerg');
INSERT INTO City VALUES (4600, 'Køge');
INSERT INTO City VALUES (4621, 'Gadstrup');
INSERT INTO City VALUES (4622, 'Havdrup');
INSERT INTO City VALUES (4623, 'Lille Skensved');
INSERT INTO City VALUES (4632, 'Bjæverskov');
INSERT INTO City VALUES (4640, 'Faxe');
INSERT INTO City VALUES (4652, 'Hårlev');
INSERT INTO City VALUES (4653, 'Karise');
INSERT INTO City VALUES (4654, 'Faxe Ladeplads');
INSERT INTO City VALUES (4660, 'Store Heddinge');
INSERT INTO City VALUES (4671, 'Strøby');
INSERT INTO City VALUES (4672, 'Klippinge');
INSERT INTO City VALUES (4673, 'Rødvig Stevns');
INSERT INTO City VALUES (4681, 'Herfølge');
INSERT INTO City VALUES (4682, 'Tureby');
INSERT INTO City VALUES (4683, 'Rønnede');
INSERT INTO City VALUES (4684, 'Holmegaard');
INSERT INTO City VALUES (4690, 'Haslev');
INSERT INTO City VALUES (4700, 'Næstved');
INSERT INTO City VALUES (4720, 'Præstø');
INSERT INTO City VALUES (4733, 'Tappernøje');
INSERT INTO City VALUES (4735, 'Mern');
INSERT INTO City VALUES (4736, 'Karrebæksminde');
INSERT INTO City VALUES (4750, 'Lundby');
INSERT INTO City VALUES (4760, 'Vordingborg');
INSERT INTO City VALUES (4771, 'Kalvehave');
INSERT INTO City VALUES (4772, 'Langebæk');
INSERT INTO City VALUES (4773, 'Stensved');
INSERT INTO City VALUES (4780, 'Stege');
INSERT INTO City VALUES (4791, 'Borre');
INSERT INTO City VALUES (4792, 'Askeby');
INSERT INTO City VALUES (4793, 'Bogø By');
INSERT INTO City VALUES (4800, 'Nykøbing F');
INSERT INTO City VALUES (4840, 'Nørre Alslev');
INSERT INTO City VALUES (4850, 'Stubbekøbing');
INSERT INTO City VALUES (4862, 'Guldborg');
INSERT INTO City VALUES (4863, 'Eskilstrup');
INSERT INTO City VALUES (4871, 'Horbelev');
INSERT INTO City VALUES (4872, 'Idestrup');
INSERT INTO City VALUES (4873, 'Væggerløse');
INSERT INTO City VALUES (4874, 'Gedser');
INSERT INTO City VALUES (4880, 'Nysted');
INSERT INTO City VALUES (4891, 'Toreby L');
INSERT INTO City VALUES (4892, 'Kettinge');
INSERT INTO City VALUES (4894, 'Øster Ulslev');
INSERT INTO City VALUES (4895, 'Errindlev');
INSERT INTO City VALUES (4900, 'Nakskov');
INSERT INTO City VALUES (4912, 'Harpelunde');
INSERT INTO City VALUES (4913, 'Horslunde');
INSERT INTO City VALUES (4920, 'Søllested');
INSERT INTO City VALUES (4930, 'Maribo');
INSERT INTO City VALUES (4941, 'Bandholm');
INSERT INTO City VALUES (4942, 'Askø og Lilleø');
INSERT INTO City VALUES (4943, 'Torrig L');
INSERT INTO City VALUES (4944, 'Fejø');
INSERT INTO City VALUES (4945, 'Femø');
INSERT INTO City VALUES (4951, 'Nørreballe');
INSERT INTO City VALUES (4952, 'Stokkemarke');
INSERT INTO City VALUES (4953, 'Vesterborg');
INSERT INTO City VALUES (4960, 'Holeby');
INSERT INTO City VALUES (4970, 'Rødby');
INSERT INTO City VALUES (4983, 'Dannemare');
INSERT INTO City VALUES (4990, 'Sakskøbing');
INSERT INTO City VALUES (4992, 'Midtsjælland USF P');
INSERT INTO City VALUES (5000, 'Odense C');
INSERT INTO City VALUES (5029, 'Odense C');
INSERT INTO City VALUES (5100, 'Odense C');
INSERT INTO City VALUES (5200, 'Odense V');
INSERT INTO City VALUES (5210, 'Odense NV');
INSERT INTO City VALUES (5220, 'Odense SØ');
INSERT INTO City VALUES (5230, 'Odense M');
INSERT INTO City VALUES (5240, 'Odense NØ');
INSERT INTO City VALUES (5250, 'Odense SV');
INSERT INTO City VALUES (5260, 'Odense S');
INSERT INTO City VALUES (5270, 'Odense ');
INSERT INTO City VALUES (5290, 'Marslev');
INSERT INTO City VALUES (5300, 'Kerteminde');
INSERT INTO City VALUES (5320, 'Agedrup');
INSERT INTO City VALUES (5330, 'Munkebo');
INSERT INTO City VALUES (5350, 'Rynkeby');
INSERT INTO City VALUES (5370, 'Mesinge');
INSERT INTO City VALUES (5380, 'Dalby');
INSERT INTO City VALUES (5390, 'Martofte');
INSERT INTO City VALUES (5400, 'Bogense');
INSERT INTO City VALUES (5450, 'Otterup');
INSERT INTO City VALUES (5462, 'Morud');
INSERT INTO City VALUES (5463, 'Harndrup');
INSERT INTO City VALUES (5464, 'Brenderup Fyn');
INSERT INTO City VALUES (5466, 'Asperup');
INSERT INTO City VALUES (5471, 'Søndersø');
INSERT INTO City VALUES (5474, 'Veflinge');
INSERT INTO City VALUES (5485, 'Skamby');
INSERT INTO City VALUES (5491, 'Blommenslyst');
INSERT INTO City VALUES (5492, 'Vissenbjerg');
INSERT INTO City VALUES (5500, 'Middelfart');
INSERT INTO City VALUES (5540, 'Ullerslev');
INSERT INTO City VALUES (5550, 'Langeskov');
INSERT INTO City VALUES (5560, 'Aarup');
INSERT INTO City VALUES (5580, 'Nørre Aaby');
INSERT INTO City VALUES (5591, 'Gelsted');
INSERT INTO City VALUES (5592, 'Ejby');
INSERT INTO City VALUES (5600, 'Faaborg');
INSERT INTO City VALUES (5601, 'Lyø');
INSERT INTO City VALUES (5602, 'Avernakø');
INSERT INTO City VALUES (5603, 'Bjørnø');
INSERT INTO City VALUES (5610, 'Assens');
INSERT INTO City VALUES (5620, 'Glamsbjerg');
INSERT INTO City VALUES (5631, 'Ebberup');
INSERT INTO City VALUES (5642, 'Millinge');
INSERT INTO City VALUES (5672, 'Broby');
INSERT INTO City VALUES (5683, 'Haarby');
INSERT INTO City VALUES (5690, 'Tommerup');
INSERT INTO City VALUES (5700, 'Svendborg');
INSERT INTO City VALUES (5750, 'Ringe');
INSERT INTO City VALUES (5762, 'Vester Skerninge');
INSERT INTO City VALUES (5771, 'Stenstrup');
INSERT INTO City VALUES (5772, 'Kværndrup');
INSERT INTO City VALUES (5792, 'Årslev');
INSERT INTO City VALUES (5800, 'Nyborg');
INSERT INTO City VALUES (5853, 'Ørbæk');
INSERT INTO City VALUES (5854, 'Gislev');
INSERT INTO City VALUES (5856, 'Ryslinge');
INSERT INTO City VALUES (5863, 'Ferritslev Fyn');
INSERT INTO City VALUES (5871, 'Frørup');
INSERT INTO City VALUES (5874, 'Hesselager');
INSERT INTO City VALUES (5881, 'Skårup Fyn');
INSERT INTO City VALUES (5882, 'Vejstrup');
INSERT INTO City VALUES (5883, 'Oure');
INSERT INTO City VALUES (5884, 'Gudme');
INSERT INTO City VALUES (5892, 'Gudbjerg Sydfyn');
INSERT INTO City VALUES (5900, 'Rudkøbing');
INSERT INTO City VALUES (5932, 'Humble');
INSERT INTO City VALUES (5935, 'Bagenkop');
INSERT INTO City VALUES (5943, 'Strynø');
INSERT INTO City VALUES (5953, 'Tranekær');
INSERT INTO City VALUES (5960, 'Marstal');
INSERT INTO City VALUES (5965, 'Birkholm');
INSERT INTO City VALUES (5970, 'Ærøskøbing');
INSERT INTO City VALUES (5985, 'Søby Ærø');
INSERT INTO City VALUES (6000, 'Kolding');
INSERT INTO City VALUES (6040, 'Egtved');
INSERT INTO City VALUES (6051, 'Almind');
INSERT INTO City VALUES (6052, 'Viuf');
INSERT INTO City VALUES (6064, 'Jordrup');
INSERT INTO City VALUES (6070, 'Christiansfeld');
INSERT INTO City VALUES (6091, 'Bjert');
INSERT INTO City VALUES (6092, 'Sønder Stenderup');
INSERT INTO City VALUES (6093, 'Sjølund');
INSERT INTO City VALUES (6094, 'Hejls');
INSERT INTO City VALUES (6100, 'Haderslev');
INSERT INTO City VALUES (6200, 'Aabenraa');
INSERT INTO City VALUES (6210, 'Barsø');
INSERT INTO City VALUES (6230, 'Rødekro');
INSERT INTO City VALUES (6240, 'Løgumkloster');
INSERT INTO City VALUES (6261, 'Bredebro');
INSERT INTO City VALUES (6270, 'Tønder');
INSERT INTO City VALUES (6280, 'Højer');
INSERT INTO City VALUES (6300, 'Gråsten');
INSERT INTO City VALUES (6310, 'Broager');
INSERT INTO City VALUES (6320, 'Egernsund');
INSERT INTO City VALUES (6330, 'Padborg');
INSERT INTO City VALUES (6340, 'Kruså');
INSERT INTO City VALUES (6360, 'Tinglev');
INSERT INTO City VALUES (6372, 'Bylderup-Bov');
INSERT INTO City VALUES (6392, 'Bolderslev');
INSERT INTO City VALUES (6400, 'Sønderborg');
INSERT INTO City VALUES (6430, 'Nordborg');
INSERT INTO City VALUES (6440, 'Augustenborg');
INSERT INTO City VALUES (6470, 'Sydals');
INSERT INTO City VALUES (6500, 'Vojens');
INSERT INTO City VALUES (6510, 'Gram');
INSERT INTO City VALUES (6520, 'Toftlund');
INSERT INTO City VALUES (6534, 'Agerskov');
INSERT INTO City VALUES (6535, 'Branderup J');
INSERT INTO City VALUES (6541, 'Bevtoft');
INSERT INTO City VALUES (6560, 'Sommersted');
INSERT INTO City VALUES (6580, 'Vamdrup');
INSERT INTO City VALUES (6600, 'Vejen');
INSERT INTO City VALUES (6621, 'Gesten');
INSERT INTO City VALUES (6622, 'Bække');
INSERT INTO City VALUES (6623, 'Vorbasse');
INSERT INTO City VALUES (6630, 'Rødding');
INSERT INTO City VALUES (6640, 'Lunderskov');
INSERT INTO City VALUES (6650, 'Brørup');
INSERT INTO City VALUES (6660, 'Lintrup');
INSERT INTO City VALUES (6670, 'Holsted');
INSERT INTO City VALUES (6682, 'Hovborg');
INSERT INTO City VALUES (6683, 'Føvling');
INSERT INTO City VALUES (6690, 'Gørding');
INSERT INTO City VALUES (6700, 'Esbjerg');
INSERT INTO City VALUES (6701, 'Esbjerg');
INSERT INTO City VALUES (6705, 'Esbjerg Ø');
INSERT INTO City VALUES (6710, 'Esbjerg V');
INSERT INTO City VALUES (6715, 'Esbjerg ');
INSERT INTO City VALUES (6720, 'Fanø');
INSERT INTO City VALUES (6731, 'Tjæreborg');
INSERT INTO City VALUES (6740, 'Bramming');
INSERT INTO City VALUES (6752, 'Glejbjerg');
INSERT INTO City VALUES (6753, 'Agerbæk');
INSERT INTO City VALUES (6760, 'Ribe');
INSERT INTO City VALUES (6771, 'Gredstedbro');
INSERT INTO City VALUES (6780, 'Skærbæk');
INSERT INTO City VALUES (6792, 'Rømø');
INSERT INTO City VALUES (6800, 'Varde');
INSERT INTO City VALUES (6818, 'Årre');
INSERT INTO City VALUES (6823, 'Ansager');
INSERT INTO City VALUES (6830, 'Nørre Nebel');
INSERT INTO City VALUES (6840, 'Oksbøl');
INSERT INTO City VALUES (6851, 'Janderup Vestj');
INSERT INTO City VALUES (6852, 'Billum');
INSERT INTO City VALUES (6853, 'Vejers Strand');
INSERT INTO City VALUES (6854, 'Henne');
INSERT INTO City VALUES (6855, 'Outrup');
INSERT INTO City VALUES (6857, 'Blåvand');
INSERT INTO City VALUES (6862, 'Tistrup');
INSERT INTO City VALUES (6870, 'Ølgod');
INSERT INTO City VALUES (6880, 'Tarm');
INSERT INTO City VALUES (6893, 'Hemmet');
INSERT INTO City VALUES (6900, 'Skjern');
INSERT INTO City VALUES (6920, 'Videbæk');
INSERT INTO City VALUES (6933, 'Kibæk');
INSERT INTO City VALUES (6940, 'Lem St');
INSERT INTO City VALUES (6950, 'Ringkøbing');
INSERT INTO City VALUES (6960, 'Hvide Sande');
INSERT INTO City VALUES (6971, 'Spjald');
INSERT INTO City VALUES (6973, 'Ørnhøj');
INSERT INTO City VALUES (6980, 'Tim');
INSERT INTO City VALUES (6990, 'Ulfborg');
INSERT INTO City VALUES (7000, 'Fredericia');
INSERT INTO City VALUES (7007, 'Fredericia');
INSERT INTO City VALUES (7017, 'Taulov Pakkecenter');
INSERT INTO City VALUES (7018, 'Pakker TLP');
INSERT INTO City VALUES (7029, 'Fredericia');
INSERT INTO City VALUES (7080, 'Børkop');
INSERT INTO City VALUES (7100, 'Vejle');
INSERT INTO City VALUES (7120, 'Vejle Øst');
INSERT INTO City VALUES (7130, 'Juelsminde');
INSERT INTO City VALUES (7140, 'Stouby');
INSERT INTO City VALUES (7150, 'Barrit');
INSERT INTO City VALUES (7160, 'Tørring');
INSERT INTO City VALUES (7171, 'Uldum');
INSERT INTO City VALUES (7173, 'Vonge');
INSERT INTO City VALUES (7182, 'Bredsten');
INSERT INTO City VALUES (7183, 'Randbøl');
INSERT INTO City VALUES (7184, 'Vandel');
INSERT INTO City VALUES (7190, 'Billund');
INSERT INTO City VALUES (7200, 'Grindsted');
INSERT INTO City VALUES (7250, 'Hejnsvig');
INSERT INTO City VALUES (7260, 'Sønder Omme');
INSERT INTO City VALUES (7270, 'Stakroge');
INSERT INTO City VALUES (7280, 'Sønder Felding');
INSERT INTO City VALUES (7300, 'Jelling');
INSERT INTO City VALUES (7321, 'Gadbjerg');
INSERT INTO City VALUES (7323, 'Give');
INSERT INTO City VALUES (7330, 'Brande');
INSERT INTO City VALUES (7361, 'Ejstrupholm');
INSERT INTO City VALUES (7362, 'Hampen');
INSERT INTO City VALUES (7400, 'Herning');
INSERT INTO City VALUES (7429, 'Herning');
INSERT INTO City VALUES (7430, 'Ikast');
INSERT INTO City VALUES (7441, 'Bording');
INSERT INTO City VALUES (7442, 'Engesvang');
INSERT INTO City VALUES (7451, 'Sunds');
INSERT INTO City VALUES (7470, 'Karup J');
INSERT INTO City VALUES (7480, 'Vildbjerg');
INSERT INTO City VALUES (7490, 'Aulum');
INSERT INTO City VALUES (7500, 'Holstebro');
INSERT INTO City VALUES (7540, 'Haderup');
INSERT INTO City VALUES (7550, 'Sørvad');
INSERT INTO City VALUES (7560, 'Hjerm');
INSERT INTO City VALUES (7570, 'Vemb');
INSERT INTO City VALUES (7600, 'Struer');
INSERT INTO City VALUES (7620, 'Lemvig');
INSERT INTO City VALUES (7650, 'Bøvlingbjerg');
INSERT INTO City VALUES (7660, 'Bækmarksbro');
INSERT INTO City VALUES (7673, 'Harboøre');
INSERT INTO City VALUES (7680, 'Thyborøn');
INSERT INTO City VALUES (7700, 'Thisted');
INSERT INTO City VALUES (7730, 'Hanstholm');
INSERT INTO City VALUES (7741, 'Frøstrup');
INSERT INTO City VALUES (7742, 'Vesløs');
INSERT INTO City VALUES (7752, 'Snedsted');
INSERT INTO City VALUES (7755, 'Bedsted Thy');
INSERT INTO City VALUES (7760, 'Hurup Thy');
INSERT INTO City VALUES (7770, 'Vestervig');
INSERT INTO City VALUES (7790, 'Thyholm');
INSERT INTO City VALUES (7800, 'Skive');
INSERT INTO City VALUES (7830, 'Vinderup');
INSERT INTO City VALUES (7840, 'Højslev');
INSERT INTO City VALUES (7850, 'Stoholm Jyll');
INSERT INTO City VALUES (7860, 'Spøttrup');
INSERT INTO City VALUES (7870, 'Roslev');
INSERT INTO City VALUES (7884, 'Fur');
INSERT INTO City VALUES (7900, 'Nykøbing M');
INSERT INTO City VALUES (7950, 'Erslev');
INSERT INTO City VALUES (7960, 'Karby');
INSERT INTO City VALUES (7970, 'Redsted M');
INSERT INTO City VALUES (7980, 'Vils');
INSERT INTO City VALUES (7990, 'Øster Assels');
INSERT INTO City VALUES (7992, 'Sydjylland/Fyn USF P');
INSERT INTO City VALUES (7993, 'Sydjylland/Fyn USF B');
INSERT INTO City VALUES (7996, 'Fakturaservice');
INSERT INTO City VALUES (7997, 'Fakturascanning');
INSERT INTO City VALUES (7998, 'Statsservice');
INSERT INTO City VALUES (7999, 'Kommunepost');
INSERT INTO City VALUES (8000, 'Aarhus C');
INSERT INTO City VALUES (8100, 'Aarhus C');
INSERT INTO City VALUES (8200, 'Aarhus ');
INSERT INTO City VALUES (8210, 'Aarhus V');
INSERT INTO City VALUES (8220, 'Brabrand');
INSERT INTO City VALUES (8229, 'Risskov Ø');
INSERT INTO City VALUES (8230, 'Åbyhøj');
INSERT INTO City VALUES (8240, 'Risskov');
INSERT INTO City VALUES (8245, 'Risskov Ø');
INSERT INTO City VALUES (8250, 'Egå');
INSERT INTO City VALUES (8260, 'Viby J');
INSERT INTO City VALUES (8270, 'Højbjerg');
INSERT INTO City VALUES (8300, 'Odder');
INSERT INTO City VALUES (8305, 'Samsø');
INSERT INTO City VALUES (8310, 'Tranbjerg J');
INSERT INTO City VALUES (8320, 'Mårslet');
INSERT INTO City VALUES (8330, 'Beder');
INSERT INTO City VALUES (8340, 'Malling');
INSERT INTO City VALUES (8350, 'Hundslund');
INSERT INTO City VALUES (8355, 'Solbjerg');
INSERT INTO City VALUES (8361, 'Hasselager');
INSERT INTO City VALUES (8362, 'Hørning');
INSERT INTO City VALUES (8370, 'Hadsten');
INSERT INTO City VALUES (8380, 'Trige');
INSERT INTO City VALUES (8381, 'Tilst');
INSERT INTO City VALUES (8382, 'Hinnerup');
INSERT INTO City VALUES (8400, 'Ebeltoft');
INSERT INTO City VALUES (8410, 'Rønde');
INSERT INTO City VALUES (8420, 'Knebel');
INSERT INTO City VALUES (8444, 'Balle');
INSERT INTO City VALUES (8450, 'Hammel');
INSERT INTO City VALUES (8462, 'Harlev J');
INSERT INTO City VALUES (8464, 'Galten');
INSERT INTO City VALUES (8471, 'Sabro');
INSERT INTO City VALUES (8472, 'Sporup');
INSERT INTO City VALUES (8500, 'Grenaa');
INSERT INTO City VALUES (8520, 'Lystrup');
INSERT INTO City VALUES (8530, 'Hjortshøj');
INSERT INTO City VALUES (8541, 'Skødstrup');
INSERT INTO City VALUES (8543, 'Hornslet');
INSERT INTO City VALUES (8544, 'Mørke');
INSERT INTO City VALUES (8550, 'Ryomgård');
INSERT INTO City VALUES (8560, 'Kolind');
INSERT INTO City VALUES (8570, 'Trustrup');
INSERT INTO City VALUES (8581, 'Nimtofte');
INSERT INTO City VALUES (8585, 'Glesborg');
INSERT INTO City VALUES (8586, 'Ørum Djurs');
INSERT INTO City VALUES (8592, 'Anholt');
INSERT INTO City VALUES (8600, 'Silkeborg');
INSERT INTO City VALUES (8620, 'Kjellerup');
INSERT INTO City VALUES (8632, 'Lemming');
INSERT INTO City VALUES (8641, 'Sorring');
INSERT INTO City VALUES (8643, 'Ans By');
INSERT INTO City VALUES (8653, 'Them');
INSERT INTO City VALUES (8654, 'Bryrup');
INSERT INTO City VALUES (8660, 'Skanderborg');
INSERT INTO City VALUES (8670, 'Låsby');
INSERT INTO City VALUES (8680, 'Ry');
INSERT INTO City VALUES (8700, 'Horsens');
INSERT INTO City VALUES (8721, 'Daugård');
INSERT INTO City VALUES (8722, 'Hedensted');
INSERT INTO City VALUES (8723, 'Løsning');
INSERT INTO City VALUES (8732, 'Hovedgård');
INSERT INTO City VALUES (8740, 'Brædstrup');
INSERT INTO City VALUES (8751, 'Gedved');
INSERT INTO City VALUES (8752, 'Østbirk');
INSERT INTO City VALUES (8762, 'Flemming');
INSERT INTO City VALUES (8763, 'Rask Mølle');
INSERT INTO City VALUES (8765, 'Klovborg');
INSERT INTO City VALUES (8766, 'Nørre Snede');
INSERT INTO City VALUES (8781, 'Stenderup');
INSERT INTO City VALUES (8783, 'Hornsyld');
INSERT INTO City VALUES (8789, 'Endelave');
INSERT INTO City VALUES (8799, 'Tunø');
INSERT INTO City VALUES (8800, 'Viborg');
INSERT INTO City VALUES (8830, 'Tjele');
INSERT INTO City VALUES (8831, 'Løgstrup');
INSERT INTO City VALUES (8832, 'Skals');
INSERT INTO City VALUES (8840, 'Rødkærsbro');
INSERT INTO City VALUES (8850, 'Bjerringbro');
INSERT INTO City VALUES (8860, 'Ulstrup');
INSERT INTO City VALUES (8870, 'Langå');
INSERT INTO City VALUES (8881, 'Thorsø');
INSERT INTO City VALUES (8882, 'Fårvang');
INSERT INTO City VALUES (8883, 'Gjern');
INSERT INTO City VALUES (8900, 'Randers C');
INSERT INTO City VALUES (8920, 'Randers NV');
INSERT INTO City VALUES (8930, 'Randers NØ');
INSERT INTO City VALUES (8940, 'Randers SV');
INSERT INTO City VALUES (8950, 'Ørsted');
INSERT INTO City VALUES (8960, 'Randers SØ');
INSERT INTO City VALUES (8961, 'Allingåbro');
INSERT INTO City VALUES (8963, 'Auning');
INSERT INTO City VALUES (8970, 'Havndal');
INSERT INTO City VALUES (8981, 'Spentrup');
INSERT INTO City VALUES (8983, 'Gjerlev J');
INSERT INTO City VALUES (8990, 'Fårup');
INSERT INTO City VALUES (9000, 'Aalborg');
INSERT INTO City VALUES (9029, 'Aalborg');
INSERT INTO City VALUES (9100, 'Aalborg');
INSERT INTO City VALUES (9200, 'Aalborg SV');
INSERT INTO City VALUES (9210, 'Aalborg SØ');
INSERT INTO City VALUES (9220, 'Aalborg Øst');
INSERT INTO City VALUES (9230, 'Svenstrup J');
INSERT INTO City VALUES (9240, 'Nibe');
INSERT INTO City VALUES (9260, 'Gistrup');
INSERT INTO City VALUES (9270, 'Klarup');
INSERT INTO City VALUES (9280, 'Storvorde');
INSERT INTO City VALUES (9293, 'Kongerslev');
INSERT INTO City VALUES (9300, 'Sæby');
INSERT INTO City VALUES (9310, 'Vodskov');
INSERT INTO City VALUES (9320, 'Hjallerup');
INSERT INTO City VALUES (9330, 'Dronninglund');
INSERT INTO City VALUES (9340, 'Asaa');
INSERT INTO City VALUES (9352, 'Dybvad');
INSERT INTO City VALUES (9362, 'Gandrup');
INSERT INTO City VALUES (9370, 'Hals');
INSERT INTO City VALUES (9380, 'Vestbjerg');
INSERT INTO City VALUES (9381, 'Sulsted');
INSERT INTO City VALUES (9382, 'Tylstrup');
INSERT INTO City VALUES (9400, 'Nørresundby');
INSERT INTO City VALUES (9430, 'Vadum');
INSERT INTO City VALUES (9440, 'Aabybro');
INSERT INTO City VALUES (9460, 'Brovst');
INSERT INTO City VALUES (9480, 'Løkken');
INSERT INTO City VALUES (9490, 'Pandrup');
INSERT INTO City VALUES (9492, 'Blokhus');
INSERT INTO City VALUES (9493, 'Saltum');
INSERT INTO City VALUES (9500, 'Hobro');
INSERT INTO City VALUES (9510, 'Arden');
INSERT INTO City VALUES (9520, 'Skørping');
INSERT INTO City VALUES (9530, 'Støvring');
INSERT INTO City VALUES (9541, 'Suldrup');
INSERT INTO City VALUES (9550, 'Mariager');
INSERT INTO City VALUES (9560, 'Hadsund');
INSERT INTO City VALUES (9574, 'Bælum');
INSERT INTO City VALUES (9575, 'Terndrup');
INSERT INTO City VALUES (9600, 'Aars');
INSERT INTO City VALUES (9610, 'Nørager');
INSERT INTO City VALUES (9620, 'Aalestrup');
INSERT INTO City VALUES (9631, 'Gedsted');
INSERT INTO City VALUES (9632, 'Møldrup');
INSERT INTO City VALUES (9640, 'Farsø');
INSERT INTO City VALUES (9670, 'Løgstør');
INSERT INTO City VALUES (9681, 'Ranum');
INSERT INTO City VALUES (9690, 'Fjerritslev');
INSERT INTO City VALUES (9700, 'Brønderslev');
INSERT INTO City VALUES (9740, 'Jerslev J');
INSERT INTO City VALUES (9750, 'Østervrå');
INSERT INTO City VALUES (9760, 'Vrå');
INSERT INTO City VALUES (9800, 'Hjørring');
INSERT INTO City VALUES (9830, 'Tårs');
INSERT INTO City VALUES (9850, 'Hirtshals');
INSERT INTO City VALUES (9870, 'Sindal');
INSERT INTO City VALUES (9881, 'Bindslev');
INSERT INTO City VALUES (9900, 'Frederikshavn');
INSERT INTO City VALUES (9940, 'Læsø');
INSERT INTO City VALUES (9970, 'Strandby');
INSERT INTO City VALUES (9981, 'Jerup');
INSERT INTO City VALUES (9982, 'Ålbæk');
INSERT INTO City VALUES (9990, 'Skagen');
INSERT INTO City VALUES (9992, 'Jylland USF P');
INSERT INTO City VALUES (9993, 'Jylland USF B');
INSERT INTO City VALUES (9996, 'Fakturaservice');
INSERT INTO City VALUES (9997, 'Fakturascanning');
INSERT INTO City VALUES (9998, 'Borgerservice');
